repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['--ignore-words=codespell-ignore.txt']
        exclude: '^(codespell-ignore\.txt$|other/file/to/exclude\.txt)'
