[build-system]
requires = ["setuptools>=45",
            "setuptools_scm[toml]>=6.2",
            "wheel"]

[project]
name = "sysmg"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "sysmg/version.py"
