[build-system]
requires = ["setuptools", "wheel", "pybind11>=2.5.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "patch_mult"
version = "0.1"
description = "Matrix operations using pybind11"
authors = [{name = "Alexey Voronin"}]
